changelog:
  exclude:
    labels:
      - skip-changelog
      - duplicate
      - invalid
      - question
      - wontfix
  categories:
    - title: Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Tests
      labels:
        - test
        - tests
    - title: Maintenance
      labels:
        - chore
        - ci
        - dependencies
        - refactor
    - title: Other Changes
      labels:
        - '*'
