use rusqlite::{Connection, OptionalExtension, params};

#[cfg(test)]
mod generated_paths;

/// Application strategy for a migration.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MigrationStrategy {
    /// Creates new tables. Uses a sentinel table check for pre-tracking DBs.
    Create,
    /// Alters existing tables. Executes statements individually with optional
    /// error tolerance.
    Alter,
}

/// Definition of a single migration, auto-generated by build.rs from SQL files.
#[derive(Debug, Clone, Copy)]
pub struct MigrationDef {
    /// Unique migration ID (matches `_peekoo_migrations.id` in the database).
    pub id: &'static str,
    /// Raw SQL content of the migration file.
    pub sql: &'static str,
    /// Application strategy.
    pub strategy: MigrationStrategy,
    /// For `Create` migrations: the sentinel table whose existence indicates
    /// the migration was already applied before tracking was introduced.
    pub sentinel: Option<&'static str>,
    /// For `Alter` migrations: error message substrings to silently ignore
    /// (e.g., `"duplicate column name"`).
    pub tolerates: &'static [&'static str],
}

/// Find a migration by its ID. Panics if not found.
pub fn find_migration(id: &str) -> &'static MigrationDef {
    MIGRATIONS
        .iter()
        .find(|m| m.id == id)
        .unwrap_or_else(|| panic!("migration '{id}' not found"))
}

include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

/// Create the migrations tracking table and apply all migrations in order.
///
/// This is idempotent — calling it multiple times on the same connection
/// is safe because each migration checks whether it has already been
/// recorded before applying.
pub fn run_all_migrations(conn: &Connection) -> Result<(), String> {
    conn.execute(
        "CREATE TABLE IF NOT EXISTS _peekoo_migrations (id TEXT PRIMARY KEY)",
        [],
    )
    .map_err(|e| format!("Create migrations table error: {e}"))?;

    for m in MIGRATIONS {
        match m.strategy {
            MigrationStrategy::Create => apply_create_migration(conn, m)?,
            MigrationStrategy::Alter => apply_alter_migration(conn, m)?,
        }
    }

    Ok(())
}

/// Open an in-memory SQLite database with all migrations applied.
/// Intended for unit tests.
pub fn setup_test_db() -> Connection {
    let conn = Connection::open_in_memory().expect("open in-memory db");
    run_all_migrations(&conn).expect("apply migrations");
    conn
}

/// Apply a single migration by ID directly (bypasses the tracking table).
/// Intended for tests that need selective migration application,
/// e.g. backfill tests that insert data between migration steps.
pub fn apply_migration(conn: &Connection, id: &str) {
    let m = find_migration(id);
    conn.execute_batch(m.sql)
        .unwrap_or_else(|e| panic!("apply migration {id}: {e}"));
}

fn is_migration_applied(conn: &Connection, id: &str) -> Result<bool, String> {
    conn.query_row(
        "SELECT 1 FROM _peekoo_migrations WHERE id = ?1",
        params![id],
        |_| Ok(true),
    )
    .optional()
    .map_err(|e| format!("Check migration {id} state error: {e}"))
    .map(|opt| opt.unwrap_or(false))
}

fn record_migration(conn: &Connection, id: &str) -> Result<(), String> {
    conn.execute(
        "INSERT OR IGNORE INTO _peekoo_migrations (id) VALUES (?1)",
        params![id],
    )
    .map_err(|e| format!("Record migration {id} state error: {e}"))?;
    Ok(())
}

fn apply_create_migration(conn: &Connection, m: &MigrationDef) -> Result<(), String> {
    if is_migration_applied(conn, m.id)? {
        return Ok(());
    }

    let sentinel = m
        .sentinel
        .ok_or_else(|| format!("CREATE migration {} missing @sentinel", m.id))?;

    if !sqlite_table_exists(conn, sentinel)? {
        conn.execute_batch(m.sql)
            .map_err(|e| format!("Apply migration {} error: {e}", m.id))?;
    }

    record_migration(conn, m.id)
}

fn apply_alter_migration(conn: &Connection, m: &MigrationDef) -> Result<(), String> {
    if is_migration_applied(conn, m.id)? {
        return Ok(());
    }

    if m.tolerates.is_empty() {
        conn.execute_batch(m.sql)
            .map_err(|e| format!("Apply migration {} error: {e}", m.id))?;
    } else {
        let sql = m
            .sql
            .lines()
            .filter(|l| {
                let t = l.trim();
                !["@migrate:", "@id:", "@sentinel:", "@tolerates:"]
                    .iter()
                    .any(|tag| t.starts_with("--") && t[2..].trim_start().starts_with(tag))
            })
            .collect::<Vec<_>>()
            .join("\n");

        for statement in sql.split(';') {
            let stmt = statement.trim();
            if stmt.is_empty() {
                continue;
            }
            if let Err(e) = conn.execute(stmt, []) {
                let e_str = e.to_string();
                if !m.tolerates.iter().any(|t| e_str.contains(t)) {
                    return Err(format!("Apply migration {} error: {e}", m.id));
                }
            }
        }
    }

    record_migration(conn, m.id)
}

fn sqlite_table_exists(conn: &Connection, table_name: &str) -> Result<bool, String> {
    conn.query_row(
        "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?1 LIMIT 1",
        params![table_name],
        |_| Ok(true),
    )
    .optional()
    .map_err(|e| format!("Query sqlite_master error: {e}"))
    .map(|opt| opt.unwrap_or(false))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_migrations_present() {
        assert!(
            MIGRATIONS.len() >= 15,
            "expected at least 15 migrations, got {}",
            MIGRATIONS.len()
        );
    }

    #[test]
    fn all_migrations_have_valid_metadata() {
        for m in MIGRATIONS {
            assert!(!m.id.is_empty(), "migration has empty id");
            if m.strategy == MigrationStrategy::Create {
                assert!(
                    m.sentinel.is_some(),
                    "create migration {} missing sentinel",
                    m.id
                );
            }
        }
    }

    #[test]
    fn migration_ids_are_sorted() {
        // Legacy migrations use @id overrides like "0001_init"; new migrations
        // default to their filename stem (e.g., "202607010001_foo"). Lexicographic
        // ordering holds because all "0*" IDs sort before "2*" timestamps.
        for window in MIGRATIONS.windows(2) {
            assert!(
                window[0].id < window[1].id,
                "migrations not sorted: {} should come before {}",
                window[0].id,
                window[1].id
            );
        }
    }

    #[test]
    fn create_migrations_contain_create_table() {
        for m in MIGRATIONS
            .iter()
            .filter(|m| m.strategy == MigrationStrategy::Create)
        {
            assert!(
                m.sql.to_uppercase().contains("CREATE TABLE"),
                "create migration {} has no CREATE TABLE statement",
                m.id
            );
        }
    }

    #[test]
    fn alter_migrations_with_add_column_have_tolerance() {
        for m in MIGRATIONS
            .iter()
            .filter(|m| m.strategy == MigrationStrategy::Alter)
        {
            if m.sql.to_uppercase().contains("ADD COLUMN") {
                assert!(
                    m.tolerates.iter().any(|t| t.contains("duplicate column")),
                    "alter migration {} uses ADD COLUMN but missing 'duplicate column name' tolerates",
                    m.id
                );
            }
        }
    }

    #[test]
    fn acp_runtime_tables_and_session_columns_exist() {
        let conn = setup_test_db();

        for table in ["agent_runtimes", "runtime_llm_providers", "runtime_models"] {
            assert!(sqlite_table_exists(&conn, table).expect("query sqlite_master"));
        }

        let mut stmt = conn
            .prepare("PRAGMA table_info(agent_sessions)")
            .expect("prepare table_info");
        let columns: Vec<String> = stmt
            .query_map([], |row| row.get(1))
            .expect("query columns")
            .collect::<Result<_, _>>()
            .expect("collect columns");

        assert!(columns.iter().any(|column| column == "runtime_id"));
        assert!(columns.iter().any(|column| column == "llm_provider_id"));
        assert!(columns.iter().any(|column| column == "model_id"));
    }

    #[test]
    fn known_migration_ids_present() {
        let ids: Vec<&str> = MIGRATIONS.iter().map(|m| m.id).collect();
        assert!(ids.contains(&"0001_init"), "missing 0001_init");
        assert!(
            ids.contains(&"0002_agent_settings"),
            "missing 0002_agent_settings"
        );
        assert!(
            ids.contains(&"0009_agent_task_assignment"),
            "missing 0009_agent_task_assignment"
        );
        assert!(
            ids.contains(&"0010_pomodoro_runtime"),
            "missing 0010_pomodoro_runtime"
        );
    }

    #[test]
    fn run_all_migrations_idempotent() {
        let conn = setup_test_db();
        run_all_migrations(&conn).expect("second run should succeed");
    }
}
