/// Definition of a single migration, auto-generated by build.rs from SQL files.
#[derive(Debug, Clone)]
pub struct MigrationDef {
    /// Unique migration ID (matches `_peekoo_migrations.id` in the database).
    pub id: &'static str,
    /// Raw SQL content of the migration file.
    pub sql: &'static str,
    /// Application strategy: `"create"` or `"alter"`.
    pub strategy: &'static str,
    /// For `create` migrations: the sentinel table whose existence indicates
    /// the migration was already applied before tracking was introduced.
    pub sentinel: Option<&'static str>,
    /// For `alter` migrations: error message substrings to silently ignore
    /// (e.g., `"duplicate column name"`).
    pub tolerates: &'static [&'static str],
}

include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_migrations_present() {
        assert!(
            MIGRATIONS.len() >= 15,
            "expected at least 15 migrations, got {}",
            MIGRATIONS.len()
        );
    }

    #[test]
    fn all_migrations_have_valid_metadata() {
        for m in MIGRATIONS {
            assert!(!m.id.is_empty(), "migration has empty id");
            assert!(
                m.strategy == "create" || m.strategy == "alter",
                "unknown strategy '{}' in {}",
                m.strategy,
                m.id
            );
            if m.strategy == "create" {
                assert!(
                    m.sentinel.is_some(),
                    "create migration {} missing sentinel",
                    m.id
                );
            }
        }
    }

    #[test]
    fn migrations_are_sorted_by_filename() {
        for window in MIGRATIONS.windows(2) {
            assert!(
                window[0].id < window[1].id,
                "migrations not sorted: {} should come before {}",
                window[0].id,
                window[1].id
            );
        }
    }

    #[test]
    fn create_migrations_contain_create_table() {
        for m in MIGRATIONS.iter().filter(|m| m.strategy == "create") {
            assert!(
                m.sql.to_uppercase().contains("CREATE TABLE"),
                "create migration {} has no CREATE TABLE statement",
                m.id
            );
        }
    }

    #[test]
    fn alter_migrations_with_add_column_have_tolerance() {
        for m in MIGRATIONS.iter().filter(|m| m.strategy == "alter") {
            if m.sql.to_uppercase().contains("ADD COLUMN") {
                assert!(
                    m.tolerates.iter().any(|t| t.contains("duplicate column")),
                    "alter migration {} uses ADD COLUMN but missing 'duplicate column name' tolerates",
                    m.id
                );
            }
        }
    }

    #[test]
    fn known_migration_ids_present() {
        let ids: Vec<&str> = MIGRATIONS.iter().map(|m| m.id).collect();
        assert!(ids.contains(&"0001_init"), "missing 0001_init");
        assert!(
            ids.contains(&"0002_agent_settings"),
            "missing 0002_agent_settings"
        );
        assert!(
            ids.contains(&"0009_agent_task_assignment"),
            "missing 0009_agent_task_assignment"
        );
        assert!(
            ids.contains(&"0010_pomodoro_runtime"),
            "missing 0010_pomodoro_runtime"
        );
    }
}
